#![allow(non_camel_case_types)]
#![allow(dead_code)]

/* automatically generated by rust-bindgen */

pub type int8_t = ::libc::c_char;
pub type int16_t = ::libc::c_short;
pub type int32_t = ::libc::c_int;
pub type int64_t = ::libc::c_longlong;
pub type uint8_t = ::libc::c_uchar;
pub type uint16_t = ::libc::c_ushort;
pub type uint32_t = ::libc::c_uint;
pub type uint64_t = ::libc::c_ulonglong;
pub type int_least8_t = ::libc::c_char;
pub type int_least16_t = ::libc::c_short;
pub type int_least32_t = ::libc::c_int;
pub type int_least64_t = ::libc::c_longlong;
pub type uint_least8_t = ::libc::c_uchar;
pub type uint_least16_t = ::libc::c_ushort;
pub type uint_least32_t = ::libc::c_uint;
pub type uint_least64_t = ::libc::c_ulonglong;
pub type int_fast8_t = ::libc::c_char;
pub type int_fast16_t = ::libc::c_int;
pub type int_fast32_t = ::libc::c_int;
pub type int_fast64_t = ::libc::c_longlong;
pub type uint_fast8_t = ::libc::c_uchar;
pub type uint_fast16_t = ::libc::c_uint;
pub type uint_fast32_t = ::libc::c_uint;
pub type uint_fast64_t = ::libc::c_ulonglong;
pub type intptr_t = ::libc::c_int;
pub type uintptr_t = ::libc::c_uint;
pub type intmax_t = ::libc::c_longlong;
pub type uintmax_t = ::libc::c_ulonglong;
pub type Enum_Unnamed1 = ::libc::c_uint;
pub const PROTOCOL_BINARY_REQ: ::libc::c_uint = 128;
pub const PROTOCOL_BINARY_RES: ::libc::c_uint = 129;
pub type protocol_binary_magic = Enum_Unnamed1;
pub type Enum_Unnamed2 = ::libc::c_uint;
pub const PROTOCOL_BINARY_RESPONSE_SUCCESS: ::libc::c_uint = 0;
pub const PROTOCOL_BINARY_RESPONSE_KEY_ENOENT: ::libc::c_uint = 1;
pub const PROTOCOL_BINARY_RESPONSE_KEY_EEXISTS: ::libc::c_uint = 2;
pub const PROTOCOL_BINARY_RESPONSE_E2BIG: ::libc::c_uint = 3;
pub const PROTOCOL_BINARY_RESPONSE_EINVAL: ::libc::c_uint = 4;
pub const PROTOCOL_BINARY_RESPONSE_NOT_STORED: ::libc::c_uint = 5;
pub const PROTOCOL_BINARY_RESPONSE_DELTA_BADVAL: ::libc::c_uint = 6;
pub const PROTOCOL_BINARY_RESPONSE_AUTH_ERROR: ::libc::c_uint = 32;
pub const PROTOCOL_BINARY_RESPONSE_AUTH_CONTINUE: ::libc::c_uint = 33;
pub const PROTOCOL_BINARY_RESPONSE_UNKNOWN_COMMAND: ::libc::c_uint = 129;
pub const PROTOCOL_BINARY_RESPONSE_ENOMEM: ::libc::c_uint = 130;
pub type protocol_binary_response_status = Enum_Unnamed2;
pub type Enum_Unnamed3 = ::libc::c_uint;
pub const PROTOCOL_BINARY_CMD_GET: ::libc::c_uint = 0;
pub const PROTOCOL_BINARY_CMD_SET: ::libc::c_uint = 1;
pub const PROTOCOL_BINARY_CMD_ADD: ::libc::c_uint = 2;
pub const PROTOCOL_BINARY_CMD_REPLACE: ::libc::c_uint = 3;
pub const PROTOCOL_BINARY_CMD_DELETE: ::libc::c_uint = 4;
pub const PROTOCOL_BINARY_CMD_INCREMENT: ::libc::c_uint = 5;
pub const PROTOCOL_BINARY_CMD_DECREMENT: ::libc::c_uint = 6;
pub const PROTOCOL_BINARY_CMD_QUIT: ::libc::c_uint = 7;
pub const PROTOCOL_BINARY_CMD_FLUSH: ::libc::c_uint = 8;
pub const PROTOCOL_BINARY_CMD_GETQ: ::libc::c_uint = 9;
pub const PROTOCOL_BINARY_CMD_NOOP: ::libc::c_uint = 10;
pub const PROTOCOL_BINARY_CMD_VERSION: ::libc::c_uint = 11;
pub const PROTOCOL_BINARY_CMD_GETK: ::libc::c_uint = 12;
pub const PROTOCOL_BINARY_CMD_GETKQ: ::libc::c_uint = 13;
pub const PROTOCOL_BINARY_CMD_APPEND: ::libc::c_uint = 14;
pub const PROTOCOL_BINARY_CMD_PREPEND: ::libc::c_uint = 15;
pub const PROTOCOL_BINARY_CMD_STAT: ::libc::c_uint = 16;
pub const PROTOCOL_BINARY_CMD_SETQ: ::libc::c_uint = 17;
pub const PROTOCOL_BINARY_CMD_ADDQ: ::libc::c_uint = 18;
pub const PROTOCOL_BINARY_CMD_REPLACEQ: ::libc::c_uint = 19;
pub const PROTOCOL_BINARY_CMD_DELETEQ: ::libc::c_uint = 20;
pub const PROTOCOL_BINARY_CMD_INCREMENTQ: ::libc::c_uint = 21;
pub const PROTOCOL_BINARY_CMD_DECREMENTQ: ::libc::c_uint = 22;
pub const PROTOCOL_BINARY_CMD_QUITQ: ::libc::c_uint = 23;
pub const PROTOCOL_BINARY_CMD_FLUSHQ: ::libc::c_uint = 24;
pub const PROTOCOL_BINARY_CMD_APPENDQ: ::libc::c_uint = 25;
pub const PROTOCOL_BINARY_CMD_PREPENDQ: ::libc::c_uint = 26;
pub const PROTOCOL_BINARY_CMD_TOUCH: ::libc::c_uint = 28;
pub const PROTOCOL_BINARY_CMD_GAT: ::libc::c_uint = 29;
pub const PROTOCOL_BINARY_CMD_GATQ: ::libc::c_uint = 30;
pub const PROTOCOL_BINARY_CMD_GATK: ::libc::c_uint = 35;
pub const PROTOCOL_BINARY_CMD_GATKQ: ::libc::c_uint = 36;
pub const PROTOCOL_BINARY_CMD_SASL_LIST_MECHS: ::libc::c_uint = 32;
pub const PROTOCOL_BINARY_CMD_SASL_AUTH: ::libc::c_uint = 33;
pub const PROTOCOL_BINARY_CMD_SASL_STEP: ::libc::c_uint = 34;
pub const PROTOCOL_BINARY_CMD_RGET: ::libc::c_uint = 48;
pub const PROTOCOL_BINARY_CMD_RSET: ::libc::c_uint = 49;
pub const PROTOCOL_BINARY_CMD_RSETQ: ::libc::c_uint = 50;
pub const PROTOCOL_BINARY_CMD_RAPPEND: ::libc::c_uint = 51;
pub const PROTOCOL_BINARY_CMD_RAPPENDQ: ::libc::c_uint = 52;
pub const PROTOCOL_BINARY_CMD_RPREPEND: ::libc::c_uint = 53;
pub const PROTOCOL_BINARY_CMD_RPREPENDQ: ::libc::c_uint = 54;
pub const PROTOCOL_BINARY_CMD_RDELETE: ::libc::c_uint = 55;
pub const PROTOCOL_BINARY_CMD_RDELETEQ: ::libc::c_uint = 56;
pub const PROTOCOL_BINARY_CMD_RINCR: ::libc::c_uint = 57;
pub const PROTOCOL_BINARY_CMD_RINCRQ: ::libc::c_uint = 58;
pub const PROTOCOL_BINARY_CMD_RDECR: ::libc::c_uint = 59;
pub const PROTOCOL_BINARY_CMD_RDECRQ: ::libc::c_uint = 60;
pub type protocol_binary_command = Enum_Unnamed3;
pub type Enum_Unnamed4 = ::libc::c_uint;
pub const PROTOCOL_BINARY_RAW_BYTES: ::libc::c_uint = 0;
pub type protocol_binary_datatypes = Enum_Unnamed4;

#[repr(C)]
pub struct Struct_Unnamed6 {
    pub magic: u8,
    pub opcode: u8,
    pub keylen: u16,
    pub extlen: u8,
    pub datatype: u8,
    pub reserved: u16,
    pub bodylen: u32,
    pub opaque: u32,
    pub cas: u64,
}
pub type protocol_binary_request_header =Struct_Unnamed6; 
#[repr(C)]
pub struct Struct_Unnamed8 {
    pub magic: u8,
    pub opcode: u8,
    pub keylen: u16,
    pub extlen: u8,
    pub datatype: u8,
    pub status: u16,
    pub bodylen: u32,
    pub opaque: u32,
    pub cas: u64,
}
pub type protocol_binary_response_header = Struct_Unnamed8;
pub type protocol_binary_request_no_extras = protocol_binary_request_header;
pub type protocol_binary_response_no_extras = protocol_binary_response_header;
pub type protocol_binary_request_get = protocol_binary_request_no_extras;
pub type protocol_binary_request_getq = protocol_binary_request_no_extras;
pub type protocol_binary_request_getk = protocol_binary_request_no_extras;
pub type protocol_binary_request_getkq = protocol_binary_request_no_extras;
#[repr(C)]
pub struct Struct_Unnamed14 {
    pub header: protocol_binary_response_header,
    pub flags: u32
}
pub type protocol_binary_response_get = Struct_Unnamed14;
pub type protocol_binary_response_getq = protocol_binary_response_get;
pub type protocol_binary_response_getk = protocol_binary_response_get;
pub type protocol_binary_response_getkq = protocol_binary_response_get;
pub type protocol_binary_request_delete = protocol_binary_request_no_extras;
pub type protocol_binary_response_delete = protocol_binary_response_no_extras;
#[repr(C)]
pub struct Struct_Unnamed17 {
    pub header: protocol_binary_request_header,
    pub expiration: u32,
}

pub type protocol_binary_request_flush = Struct_Unnamed17 ;
pub type protocol_binary_response_flush = protocol_binary_response_no_extras;
#[repr(C)]
pub struct Struct_Unnamed20 {
    pub header: protocol_binary_request_header,
    pub flags: u32,
    pub expiration: u32,
}
pub type protocol_binary_request_set =Struct_Unnamed20 ;
pub type protocol_binary_request_add = protocol_binary_request_set;
pub type protocol_binary_request_replace = protocol_binary_request_set;
pub type protocol_binary_response_set = protocol_binary_response_no_extras;
pub type protocol_binary_response_add = protocol_binary_response_no_extras;
pub type protocol_binary_response_replace = protocol_binary_response_no_extras;
pub type protocol_binary_request_noop = protocol_binary_request_no_extras;
pub type protocol_binary_response_noop = protocol_binary_response_no_extras;
#[repr(C)]
pub struct Struct_Unnamed23 {
    pub header: protocol_binary_request_header,
    pub delta: u64,
    pub initial: u64,
    pub expiration: u32,
}
pub type protocol_binary_request_incr = Struct_Unnamed23;
pub type protocol_binary_request_decr = protocol_binary_request_incr;
#[repr(C)]
pub struct Struct_Unnamed26 {
    pub header: protocol_binary_response_header,
    pub value: u64,
}
pub type protocol_binary_response_incr = Struct_Unnamed26;
pub type protocol_binary_response_decr = protocol_binary_response_incr;
pub type protocol_binary_request_quit = protocol_binary_request_no_extras;
pub type protocol_binary_response_quit = protocol_binary_response_no_extras;
pub type protocol_binary_request_append = protocol_binary_request_no_extras;
pub type protocol_binary_request_prepend = protocol_binary_request_no_extras;
pub type protocol_binary_response_append = protocol_binary_response_no_extras;
pub type protocol_binary_response_prepend = protocol_binary_response_no_extras;
pub type protocol_binary_request_version = protocol_binary_request_no_extras;
pub type protocol_binary_response_version = protocol_binary_response_no_extras;
pub type protocol_binary_request_stats = protocol_binary_request_no_extras;
pub type protocol_binary_response_stats = protocol_binary_response_no_extras;
#[repr(C)]
pub struct Struct_Unnamed29 {
    pub header: protocol_binary_request_header,
    pub expiration: u32,
}
pub type protocol_binary_request_touch = Struct_Unnamed29;
pub type protocol_binary_response_touch = protocol_binary_response_no_extras;
#[repr(C)]
pub struct Struct_Unnamed32 {
    pub header: protocol_binary_request_header,
    pub expiration: u32,
}
pub type protocol_binary_request_gat = Struct_Unnamed32;
pub type protocol_binary_request_gatq = protocol_binary_request_gat;
pub type protocol_binary_request_gatk = protocol_binary_request_gat;
pub type protocol_binary_request_gatkq = protocol_binary_request_gat;
pub type protocol_binary_response_gat = protocol_binary_response_get;
pub type protocol_binary_response_gatq = protocol_binary_response_get;
pub type protocol_binary_response_gatk = protocol_binary_response_get;
pub type protocol_binary_response_gatkq = protocol_binary_response_get;
#[repr(C)]
pub struct Struct_Unnamed35 {
    pub header: protocol_binary_response_header,
    pub size: u16,
    pub reserved: u8,
    pub flags: u8,
    pub max_results: u32,
}
pub type protocol_binary_request_rangeop = Struct_Unnamed35;
pub type protocol_binary_request_rget = protocol_binary_request_rangeop;
pub type protocol_binary_request_rset = protocol_binary_request_rangeop;
pub type protocol_binary_request_rsetq = protocol_binary_request_rangeop;
pub type protocol_binary_request_rappend = protocol_binary_request_rangeop;
pub type protocol_binary_request_rappendq = protocol_binary_request_rangeop;
pub type protocol_binary_request_rprepend = protocol_binary_request_rangeop;
pub type protocol_binary_request_rprependq = protocol_binary_request_rangeop;
pub type protocol_binary_request_rdelete = protocol_binary_request_rangeop;
pub type protocol_binary_request_rdeleteq = protocol_binary_request_rangeop;
pub type protocol_binary_request_rincr = protocol_binary_request_rangeop;
pub type protocol_binary_request_rincrq = protocol_binary_request_rangeop;
pub type protocol_binary_request_rdecr = protocol_binary_request_rangeop;
pub type protocol_binary_request_rdecrq = protocol_binary_request_rangeop;
